'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class SolutionInspector
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DWSIM.Interfaces.SolutionInspector", GetType(SolutionInspector).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Acentric Factors: {0}.
        '''</summary>
        Public Shared ReadOnly Property Acentric_Factors_0() As String
            Get
                Return ResourceManager.GetString("Acentric_Factors_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Beggs and Brill Multiphase Pressure Drop Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Beggs_and_Brill_Multiphase_Pressure_Drop_Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Beggs_and_Brill_Multiphase_Pressure_Drop_Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Beggs and Brill Pressure Drop.
        '''</summary>
        Public Shared ReadOnly Property Beggs_and_Brill_Pressure_Drop() As String
            Get
                Return ResourceManager.GetString("Beggs_and_Brill_Pressure_Drop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculated/Estimated HTC: {0} W/[m2.K].
        '''</summary>
        Public Shared ReadOnly Property Calculated_Estimated_HTC_0_W_m2_K() As String
            Get
                Return ResourceManager.GetString("Calculated_Estimated_HTC_0_W_m2_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculated Heat Transfer Area: {0} m2.
        '''</summary>
        Public Shared ReadOnly Property Calculated_Heat_Transfer_Area_0_m2() As String
            Get
                Return ResourceManager.GetString("Calculated_Heat_Transfer_Area_0_m2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;h2&gt;Calculated Intermediate Parameters&lt;/h2&gt;.
        '''</summary>
        Public Shared ReadOnly Property Calculated_Intermediate_Parameters() As String
            Get
                Return ResourceManager.GetString("Calculated_Intermediate_Parameters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculated outlet pressure: {0} Pa.
        '''</summary>
        Public Shared ReadOnly Property Calculated_outlet_pressure_0_Pa() As String
            Get
                Return ResourceManager.GetString("Calculated_outlet_pressure_0_Pa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculated Outlet Temperature: {0} K.
        '''</summary>
        Public Shared ReadOnly Property Calculated_Outlet_Temperature_0_K() As String
            Get
                Return ResourceManager.GetString("Calculated_Outlet_Temperature_0_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;h2&gt;Calculated Parameters&lt;/h2&gt;.
        '''</summary>
        Public Shared ReadOnly Property Calculated_Parameters() As String
            Get
                Return ResourceManager.GetString("Calculated_Parameters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculated/Specified Heat Transfer: {0} kW.
        '''</summary>
        Public Shared ReadOnly Property Calculated_Specified_Heat_Transfer_0_kW() As String
            Get
                Return ResourceManager.GetString("Calculated_Specified_Heat_Transfer_0_kW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculating increment {0}....
        '''</summary>
        Public Shared ReadOnly Property Calculating_increment_0() As String
            Get
                Return ResourceManager.GetString("Calculating_increment_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculating segment {0} ({1}/{2})....
        '''</summary>
        Public Shared ReadOnly Property Calculating_segment_0_1_2() As String
            Get
                Return ResourceManager.GetString("Calculating_segment_0_1_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculation Type: {0}.
        '''</summary>
        Public Shared ReadOnly Property Calculation_Type_0() As String
            Get
                Return ResourceManager.GetString("Calculation_Type_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calling Pressure Drop calculation routine....
        '''</summary>
        Public Shared ReadOnly Property Calling_Pressure_Drop_calculation_routine() As String
            Get
                Return ResourceManager.GetString("Calling_Pressure_Drop_calculation_routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compounds: {0}.
        '''</summary>
        Public Shared ReadOnly Property Compounds_0() As String
            Get
                Return ResourceManager.GetString("Compounds_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compressibility Factor.
        '''</summary>
        Public Shared ReadOnly Property Compressibility_Factor() As String
            Get
                Return ResourceManager.GetString("Compressibility_Factor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compressibility Factor: {0}.
        '''</summary>
        Public Shared ReadOnly Property Compressibility_Factor_0() As String
            Get
                Return ResourceManager.GetString("Compressibility_Factor_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compressibility Factor Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Compressibility_Factor_Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Compressibility_Factor_Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Converged outlet pressure: {0} Pa.
        '''</summary>
        Public Shared ReadOnly Property Converged_outlet_pressure_0_Pa() As String
            Get
                Return ResourceManager.GetString("Converged_outlet_pressure_0_Pa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Converged Outlet Temperature: {0} K.
        '''</summary>
        Public Shared ReadOnly Property Converged_outlet_temperature_0_K() As String
            Get
                Return ResourceManager.GetString("Converged_outlet_temperature_0_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Critical Pressures: {0} Pa&quot;.
        '''</summary>
        Public Shared ReadOnly Property Critical_Pressures_0_Pa() As String
            Get
                Return ResourceManager.GetString("Critical_Pressures_0_Pa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Critical Temperatures: {0} K.
        '''</summary>
        Public Shared ReadOnly Property Critical_Temperatures_0_K() As String
            Get
                Return ResourceManager.GetString("Critical_Temperatures_0_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current Enthalpy error: {0}.
        '''</summary>
        Public Shared ReadOnly Property Current_Enthalpy_error_0() As String
            Get
                Return ResourceManager.GetString("Current_Enthalpy_error_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This is the routine responsible for the calculation of phase distribution in the currently associated Material Stream, using the specified Flash Algorithm..
        '''</summary>
        Public Shared ReadOnly Property DW_CalcEquilibrium_Paragraph_01() As String
            Get
                Return ResourceManager.GetString("DW_CalcEquilibrium_Paragraph_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The first thing that the routine does is to erase all previously calculated phase distribution and properties on the stream, if they exist..
        '''</summary>
        Public Shared ReadOnly Property DW_CalcEquilibrium_Paragraph_02() As String
            Get
                Return ResourceManager.GetString("DW_CalcEquilibrium_Paragraph_02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erasing properties....
        '''</summary>
        Public Shared ReadOnly Property DW_CalcEquilibrium_Paragraph_03() As String
            Get
                Return ResourceManager.GetString("DW_CalcEquilibrium_Paragraph_03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to It then checks for the Material Stream State Specification, in order to proceed with the correct flash (equilibrium) calculation..
        '''</summary>
        Public Shared ReadOnly Property DW_CalcEquilibrium_Paragraph_04() As String
            Get
                Return ResourceManager.GetString("DW_CalcEquilibrium_Paragraph_04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The defined specification is TP (Temperature and Pressure). DWSIM will call the &apos;Flash_PT&apos; routine from the currently associated Flash Algorithm instance..
        '''</summary>
        Public Shared ReadOnly Property DW_CalcEquilibrium_Paragraph_05() As String
            Get
                Return ResourceManager.GetString("DW_CalcEquilibrium_Paragraph_05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculating Mixture Initial Gibbs Energy....
        '''</summary>
        Public Shared ReadOnly Property DW_CalcEquilibrium_Paragraph_06() As String
            Get
                Return ResourceManager.GetString("DW_CalcEquilibrium_Paragraph_06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DWSIM will calculate PR EOS Fugacity Coefficient using the CPU..
        '''</summary>
        Public Shared ReadOnly Property DWSIM_will_calculate_PR_EOS_Fugacity_Coefficient_using_the_CPU() As String
            Get
                Return ResourceManager.GetString("DWSIM_will_calculate_PR_EOS_Fugacity_Coefficient_using_the_CPU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enthalpy: {0} kJ/kg.
        '''</summary>
        Public Shared ReadOnly Property Enthalpy_0_kJ_kg() As String
            Get
                Return ResourceManager.GetString("Enthalpy_0_kJ_kg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entropy: {0} kJ/kg.
        '''</summary>
        Public Shared ReadOnly Property Entropy_0_kJ_kg() As String
            Get
                Return ResourceManager.GetString("Entropy_0_kJ_kg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to External Diameter = {0} m.
        '''</summary>
        Public Shared ReadOnly Property External_Diameter_0_m() As String
            Get
                Return ResourceManager.GetString("External_Diameter_0_m", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to External HTC = {0} W/[m2.K].
        '''</summary>
        Public Shared ReadOnly Property External_HTC_0_W_m2_K() As String
            Get
                Return ResourceManager.GetString("External_HTC_0_W_m2_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to External Loop #{0}.
        '''</summary>
        Public Shared ReadOnly Property External_Loop_0() As String
            Get
                Return ResourceManager.GetString("External_Loop_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to External Temperature = {0} K.
        '''</summary>
        Public Shared ReadOnly Property External_Temperature_0_K() As String
            Get
                Return ResourceManager.GetString("External_Temperature_0_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flow Regime:.
        '''</summary>
        Public Shared ReadOnly Property Flow_Regime() As String
            Get
                Return ResourceManager.GetString("Flow_Regime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fluid Temperature = {0} K.
        '''</summary>
        Public Shared ReadOnly Property Fluid_Temperature_0_K() As String
            Get
                Return ResourceManager.GetString("Fluid_Temperature_0_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fugacity Coefficients: {0}.
        '''</summary>
        Public Shared ReadOnly Property Fugacity_Coefficients_0() As String
            Get
                Return ResourceManager.GetString("Fugacity_Coefficients_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ideal Gas Heat Capacities: {0}.
        '''</summary>
        Public Shared ReadOnly Property Ideal_Gas_Heat_Capacities_0() As String
            Get
                Return ResourceManager.GetString("Ideal_Gas_Heat_Capacities_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to in gas phase.
        '''</summary>
        Public Shared ReadOnly Property in_gas_phase() As String
            Get
                Return ResourceManager.GetString("in_gas_phase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to in liquid phase.
        '''</summary>
        Public Shared ReadOnly Property in_liquid_phase() As String
            Get
                Return ResourceManager.GetString("in_liquid_phase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to in the feed liquid (assumed to be known).
        '''</summary>
        Public Shared ReadOnly Property in_the_feed_liquid_assumed_to_be_known() As String
            Get
                Return ResourceManager.GetString("in_the_feed_liquid_assumed_to_be_known", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Include External HTC = {0}.
        '''</summary>
        Public Shared ReadOnly Property Include_External_HTC_0() As String
            Get
                Return ResourceManager.GetString("Include_External_HTC_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Include Insulation = {0}.
        '''</summary>
        Public Shared ReadOnly Property Include_Insulation_0() As String
            Get
                Return ResourceManager.GetString("Include_Insulation_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Include Internal HTC = {0}.
        '''</summary>
        Public Shared ReadOnly Property Include_Internal_HTC_0() As String
            Get
                Return ResourceManager.GetString("Include_Internal_HTC_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Include Pipe Wall = {0}.
        '''</summary>
        Public Shared ReadOnly Property Include_Pipe_Wall_0() As String
            Get
                Return ResourceManager.GetString("Include_Pipe_Wall_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Increment #{0}.
        '''</summary>
        Public Shared ReadOnly Property Increment_0() As String
            Get
                Return ResourceManager.GetString("Increment_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initial estimates for K: {0}.
        '''</summary>
        Public Shared ReadOnly Property Initial_estimates_for_K_0() As String
            Get
                Return ResourceManager.GetString("Initial_estimates_for_K_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initial estimate for L (1-V): {0}.
        '''</summary>
        Public Shared ReadOnly Property Initial_estimates_for_L_1_V_0() As String
            Get
                Return ResourceManager.GetString("Initial_estimates_for_L_1_V_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initial estimate for T: {0} K.
        '''</summary>
        Public Shared ReadOnly Property Initial_estimates_for_T_0_K() As String
            Get
                Return ResourceManager.GetString("Initial_estimates_for_T_0_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initial estimate for V: {0}.
        '''</summary>
        Public Shared ReadOnly Property Initial_estimates_for_V_0() As String
            Get
                Return ResourceManager.GetString("Initial_estimates_for_V_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initial estimates for x: {0}.
        '''</summary>
        Public Shared ReadOnly Property Initial_estimates_for_x_0() As String
            Get
                Return ResourceManager.GetString("Initial_estimates_for_x_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initial estimates for y: {0}.
        '''</summary>
        Public Shared ReadOnly Property Initial_estimates_for_y_0() As String
            Get
                Return ResourceManager.GetString("Initial_estimates_for_y_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inlet Enthalpy: {0} kJ/kg.
        '''</summary>
        Public Shared ReadOnly Property Inlet_Enthalpy_0_kJ_kg() As String
            Get
                Return ResourceManager.GetString("Inlet_Enthalpy_0_kJ_kg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inlet pressure: {0} Pa.
        '''</summary>
        Public Shared ReadOnly Property Inlet_pressure_0_Pa() As String
            Get
                Return ResourceManager.GetString("Inlet_pressure_0_Pa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;h3&gt;Inlet Stream #{0}&lt;/h3&gt;.
        '''</summary>
        Public Shared ReadOnly Property Inlet_Stream_0() As String
            Get
                Return ResourceManager.GetString("Inlet_Stream_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;h2&gt;Input Parameters&lt;/h2&gt;.
        '''</summary>
        Public Shared ReadOnly Property Input_Parameters() As String
            Get
                Return ResourceManager.GetString("Input_Parameters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interaction Parameters: {0}.
        '''</summary>
        Public Shared ReadOnly Property Interaction_Parameters_0() As String
            Get
                Return ResourceManager.GetString("Interaction_Parameters_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;h2&gt;Intermediate Calculations&lt;/h2&gt;.
        '''</summary>
        Public Shared ReadOnly Property Intermediate_Calculations() As String
            Get
                Return ResourceManager.GetString("Intermediate_Calculations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Internal Diameter = {0} m.
        '''</summary>
        Public Shared ReadOnly Property Internal_Diameter_0_m() As String
            Get
                Return ResourceManager.GetString("Internal_Diameter_0_m", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Internal HTC = {0} W/[m2.K].
        '''</summary>
        Public Shared ReadOnly Property Internal_HTC_0_W_m2_K() As String
            Get
                Return ResourceManager.GetString("Internal_HTC_0_W_m2_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to is the equilibrium constant of component i.
        '''</summary>
        Public Shared ReadOnly Property is_the_equilibrium_constant_of_component_i() As String
            Get
                Return ResourceManager.GetString("is_the_equilibrium_constant_of_component_i", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to is the fraction of feed that is vaporised.
        '''</summary>
        Public Shared ReadOnly Property is_the_fraction_of_feed_that_is_vaporised() As String
            Get
                Return ResourceManager.GetString("is_the_fraction_of_feed_that_is_vaporised", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to is the mole fraction of component i.
        '''</summary>
        Public Shared ReadOnly Property is_the_mole_fraction_of_component_i() As String
            Get
                Return ResourceManager.GetString("is_the_mole_fraction_of_component_i", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to K values where updated. Current values: {0}.
        '''</summary>
        Public Shared ReadOnly Property K_values_where_updated_Current_values_0() As String
            Get
                Return ResourceManager.GetString("K_values_where_updated_Current_values_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Length = {0} m.
        '''</summary>
        Public Shared ReadOnly Property Length_0_m() As String
            Get
                Return ResourceManager.GetString("Length_0_m", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liquid Holdup = {0}.
        '''</summary>
        Public Shared ReadOnly Property Liquid_Holdup_0() As String
            Get
                Return ResourceManager.GetString("Liquid_Holdup_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liquid Phase Cp = {0} kJ/[kg.K].
        '''</summary>
        Public Shared ReadOnly Property Liquid_Phase_Cp_0_kJ_kg_K() As String
            Get
                Return ResourceManager.GetString("Liquid_Phase_Cp_0_kJ_kg_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liquid Phase Density = {0} kg/m3.
        '''</summary>
        Public Shared ReadOnly Property Liquid_Phase_Density_0_kg_m3() As String
            Get
                Return ResourceManager.GetString("Liquid_Phase_Density_0_kg_m3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liquid Phase Thermal Conductivity = {0} W/[m.K].
        '''</summary>
        Public Shared ReadOnly Property Liquid_Phase_Thermal_Conductivity_0_W_m_K() As String
            Get
                Return ResourceManager.GetString("Liquid_Phase_Thermal_Conductivity_0_W_m_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liquid Phase Velocity = {0} m/s.
        '''</summary>
        Public Shared ReadOnly Property Liquid_Phase_Velocity_0_m_s() As String
            Get
                Return ResourceManager.GetString("Liquid_Phase_Velocity_0_m_s", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading reports....
        '''</summary>
        Public Shared ReadOnly Property Loading_reports() As String
            Get
                Return ResourceManager.GetString("Loading_reports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mass Flow: {0} kg/s.
        '''</summary>
        Public Shared ReadOnly Property Mass_Flow_0_kg_s() As String
            Get
                Return ResourceManager.GetString("Mass_Flow_0_kg_s", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mole Fractions: {0}.
        '''</summary>
        Public Shared ReadOnly Property Mole_Fractions_0() As String
            Get
                Return ResourceManager.GetString("Mole_Fractions_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nested Loops (VLE).
        '''</summary>
        Public Shared ReadOnly Property Nested_Loops_VLE() As String
            Get
                Return ResourceManager.GetString("Nested_Loops_VLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This routine tries to find the compositions of a liquid and a vapor phase at equilibrium by solving the Rachford-Rice equation using a newton convergence approach..
        '''</summary>
        Public Shared ReadOnly Property NestedLoop_FlashPT_01() As String
            Get
                Return ResourceManager.GetString("NestedLoop_FlashPT_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Rachford-Rice equation is.
        '''</summary>
        Public Shared ReadOnly Property NestedLoop_FlashPT_02() As String
            Get
                Return ResourceManager.GetString("NestedLoop_FlashPT_02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The equilibrium constants K&lt;sub&gt;i&lt;/sub&gt; are in general functions of many parameters, though the most important is arguably temperature; they are defined as:.
        '''</summary>
        Public Shared ReadOnly Property NestedLoop_FlashPT_03() As String
            Get
                Return ResourceManager.GetString("NestedLoop_FlashPT_03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Once the Rachford-Rice equation has been solved for &lt;math_inline&gt;\beta&lt;/math_inline&gt;, the compositions x&lt;sub&gt;i&lt;/sub&gt; and y&lt;sub&gt;i&lt;/sub&gt; can be immediately calculated as:.
        '''</summary>
        Public Shared ReadOnly Property NestedLoop_FlashPT_04() As String
            Get
                Return ResourceManager.GetString("NestedLoop_FlashPT_04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Rachford - Rice equation can have multiple solutions for &lt;math_inline&gt;\beta&lt;/math_inline&gt;, at most one of which guarantees that all &lt;math_inline&gt;x_i&lt;/math_inline&gt; and &lt;math_inline&gt;y_i&lt;/math_inline&gt; will be positive. In particular, if there is only one &lt;math_inline&gt;\beta&lt;/math_inline&gt; for which:.
        '''</summary>
        Public Shared ReadOnly Property NestedLoop_FlashPT_05() As String
            Get
                Return ResourceManager.GetString("NestedLoop_FlashPT_05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to then that &lt;math_inline&gt;\beta&lt;/math_inline&gt; is the solution; if there are multiple  such &lt;math_inline&gt;\beta&lt;/math_inline&gt;s, it means that either &lt;math_inline&gt;K_{max}&lt;1&lt;/math_inline&gt; or &lt;math_inline&gt;K_{min}&gt;1&lt;/math_inline&gt;, indicating respectively that no gas phase can be sustained (and therefore &lt;math_inline&gt;\beta=0&lt;/math_inline&gt;) or conversely that no liquid phase can exist (and therefore &lt;math_inline&gt;\beta=1&lt;/math_inline&gt;)..
        '''</summary>
        Public Shared ReadOnly Property NestedLoop_FlashPT_06() As String
            Get
                Return ResourceManager.GetString("NestedLoop_FlashPT_06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DWSIM initializes the current calculation with ideal K-values estimated from vapor pressure data for each compound, or by using previously calculated values from an earlier solution..
        '''</summary>
        Public Shared ReadOnly Property NestedLoop_FlashPT_07() As String
            Get
                Return ResourceManager.GetString("NestedLoop_FlashPT_07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This is the Newton convergence loop iteration #{0}. DWSIM will use the current values of y and x to calculate fugacity coefficients and update K using the Property Package rigorous models..
        '''</summary>
        Public Shared ReadOnly Property Newton_Iteration_Fugacity_Detail_0() As String
            Get
                Return ResourceManager.GetString("Newton_Iteration_Fugacity_Detail_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Outlet Enthalpy: {0} kJ/kg.
        '''</summary>
        Public Shared ReadOnly Property Outlet_Enthalpy_0_kJ_kg() As String
            Get
                Return ResourceManager.GetString("Outlet_Enthalpy_0_kJ_kg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overal Heat Transfer Coefficient Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Overal_Heat_Transfer_Coefficient_Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Overal_Heat_Transfer_Coefficient_Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overall HTC = {0} W/[m2.K].
        '''</summary>
        Public Shared ReadOnly Property Overall_HTC_0_W_m2_K() As String
            Get
                Return ResourceManager.GetString("Overall_HTC_0_W_m2_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overall HTC Calculation.
        '''</summary>
        Public Shared ReadOnly Property Overall_HTC_Calculation() As String
            Get
                Return ResourceManager.GetString("Overall_HTC_Calculation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Peng Robinson EOS Compressibility Factor.
        '''</summary>
        Public Shared ReadOnly Property Peng_Robinson_EOS_Compressibility_Factor() As String
            Get
                Return ResourceManager.GetString("Peng_Robinson_EOS_Compressibility_Factor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Peng Robinson EOS Compressibility Factor Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Peng_Robinson_EOS_Compressibility_Factor_Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Peng_Robinson_EOS_Compressibility_Factor_Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Peng-Robinson EOS Fugacity Coefficient.
        '''</summary>
        Public Shared ReadOnly Property Peng_Robinson_EOS_Fugacity_Coefficient() As String
            Get
                Return ResourceManager.GetString("Peng_Robinson_EOS_Fugacity_Coefficient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Peng-Robinson EOS Heat Capacity Ratio Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Peng_Robinson_EOS_Heat_Capacity_Ratio_Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Peng_Robinson_EOS_Heat_Capacity_Ratio_Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Petalas and Aziz Multiphase Pressure Drop Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Petalas_and_Aziz_Multiphase_Pressure_Drop_Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Petalas_and_Aziz_Multiphase_Pressure_Drop_Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Petalas and Aziz Pressure Drop.
        '''</summary>
        Public Shared ReadOnly Property Petalas_and_Aziz_Pressure_Drop() As String
            Get
                Return ResourceManager.GetString("Petalas_and_Aziz_Pressure_Drop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  (PH Flash - Fast Mode).
        '''</summary>
        Public Shared ReadOnly Property PH_Flash_Fast_Mode() As String
            Get
                Return ResourceManager.GetString("PH_Flash_Fast_Mode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PH Flash Newton Iteration.
        '''</summary>
        Public Shared ReadOnly Property PH_Flash_Newton_Iteration() As String
            Get
                Return ResourceManager.GetString("PH_Flash_Newton_Iteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phase 1 composition: {0}.
        '''</summary>
        Public Shared ReadOnly Property Phase_1_composition_0() As String
            Get
                Return ResourceManager.GetString("Phase_1_composition_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phase 2 composition: {0}.
        '''</summary>
        Public Shared ReadOnly Property Phase_2_composition_0() As String
            Get
                Return ResourceManager.GetString("Phase_2_composition_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  (Phase Equilibria).
        '''</summary>
        Public Shared ReadOnly Property Phase_Equilibria() As String
            Get
                Return ResourceManager.GetString("Phase_Equilibria", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Pipe Segment unit operation  can be used to 
        '''                                simulate fluid flow process in a pipe. Two of the most used 
        '''                                correlations for the calculation of pressure drop are available 
        '''                                in DWSIM. Temperature can be rigorously calculated considering 
        '''                                the influence of the environment. With the help of the Recycle 
        '''                                Logical Operation, the user can build large  [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_01() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The pipe segment is divided in sections, which can be straight 
        '''                                tubes, valves, curves, etc. Each section is subdivided in small 
        '''                                sections for calculation purposes, as defined by the user..
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_02() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The pipe segment is calculated based on incremental mass and 
        '''                            energy balances. The complete algorithm consists in three nested 
        '''                            loops. The external loop iterates on the sections (increments), 
        '''                            the middle loop iterates on the temperature and the internal loop 
        '''                            calculates the pressure. The pressure and temperature are 
        '''                            calculated as follows:.
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_03() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1. The inlet temperature and pressure are used to estimate the 
        '''                            increment outlet pressure and temperature..
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_04() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2. Fluid properties are calculated based in a arithmetic mean of 
        '''                            inlet and outlet conditions..
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_05() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3. The calculated properties and the inlet pressure are used to 
        '''                              calculate the pressure drop. With it, the outlet pressure is 
        '''                              calculated..
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_06() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4. The calculated and estimated pressure are compared, and if 
        '''                              their difference exceeds the tolerance, a new outlet pressure 
        '''                              is estimated, and the steps 2 and 3 are repeated..
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_07() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5. Once the internal loop has converged, the outlet temperature 
        '''                              is calculated. If the global heat transfer coefficient (U) was 
        '''                              given, the outlet temperature is calculated from the following 
        '''                              equation:.
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_08() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to where: Q = heat transferred, A = heat transfer area (external 
        '''                              surface) and `\Delta T_{ml}` = logarithmic mean temperature 
        '''                              difference..
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_09() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 6. The calculated temperature is compared to the estimated one, 
        '''                              and if their difference exceeds the specified tolerance, a new 
        '''                              temperature is estimated and new properties are calculated 
        '''                              (return to step 2)..
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_10() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 7. When both pressure and temperature converges, the results are 
        '''                            passed to the next increment, where calculation restarts..
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_11() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pipe Insulation HTC = {0} W/[m2.K].
        '''</summary>
        Public Shared ReadOnly Property Pipe_Insulation_HTC_0_W_m2_K() As String
            Get
                Return ResourceManager.GetString("Pipe_Insulation_HTC_0_W_m2_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pipe Roughness = {0} m.
        '''</summary>
        Public Shared ReadOnly Property Pipe_Roughness_0_m() As String
            Get
                Return ResourceManager.GetString("Pipe_Roughness_0_m", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pipe Wall HTC = {0} W/[m2.K].
        '''</summary>
        Public Shared ReadOnly Property Pipe_Wall_HTC_0_W_m2_K() As String
            Get
                Return ResourceManager.GetString("Pipe_Wall_HTC_0_W_m2_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pipe Wall Material = {0}.
        '''</summary>
        Public Shared ReadOnly Property Pipe_Wall_Material_0() As String
            Get
                Return ResourceManager.GetString("Pipe_Wall_Material_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pressure: {0} Pa.
        '''</summary>
        Public Shared ReadOnly Property Pressure_0_Pa() As String
            Get
                Return ResourceManager.GetString("Pressure_0_Pa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pressure convergence loop iteration #{0}.
        '''</summary>
        Public Shared ReadOnly Property Pressure_convergence_loop_iteration_0() As String
            Get
                Return ResourceManager.GetString("Pressure_convergence_loop_iteration_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pressure-Enthalpy Flash Algorithm (Fast Mode) Convergence Iteration Step.
        '''</summary>
        Public Shared ReadOnly Property Pressure_Entalphy_Flash_Algorithm_Convergence_Iteration_Step() As String
            Get
                Return ResourceManager.GetString("Pressure_Entalphy_Flash_Algorithm_Convergence_Iteration_Step", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This is the Newton convergence loop iteration #{0}. DWSIM will use the current value of T to calculate the phase distribution by calling the Flash_PT routine..
        '''</summary>
        Public Shared ReadOnly Property Pressure_Entalphy_Flash_Algorithm_Convergence_Iteration_Step_Detail_0() As String
            Get
                Return ResourceManager.GetString("Pressure_Entalphy_Flash_Algorithm_Convergence_Iteration_Step_Detail_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pressure-Entropy Flash Algorithm (Fast Mode) Convergence Iteration Step.
        '''</summary>
        Public Shared ReadOnly Property Pressure_Entropy_Flash_Algorithm_Fast_mode_Convergence_Iteration_Step() As String
            Get
                Return ResourceManager.GetString("Pressure_Entropy_Flash_Algorithm_Fast_mode_Convergence_Iteration_Step", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pressure Loop #{0}.
        '''</summary>
        Public Shared ReadOnly Property Pressure_Loop_0() As String
            Get
                Return ResourceManager.GetString("Pressure_Loop_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pressure-Temperature Flash Algorithm Convergence Iteration Step.
        '''</summary>
        Public Shared ReadOnly Property Pressure_Temperature_Flash_Algorithm_Convergence_Iteration_Step() As String
            Get
                Return ResourceManager.GetString("Pressure_Temperature_Flash_Algorithm_Convergence_Iteration_Step", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pressure-Temperature Flash Algorithm Routine.
        '''</summary>
        Public Shared ReadOnly Property Pressure_Temperature_Flash_Algorithm_Routine() As String
            Get
                Return ResourceManager.GetString("Pressure_Temperature_Flash_Algorithm_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proceeding with temperature convergence....
        '''</summary>
        Public Shared ReadOnly Property Proceeding_with_temperature_convergence() As String
            Get
                Return ResourceManager.GetString("Proceeding_with_temperature_convergence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Property Package Enthalpy Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Property_Package_Enthalpy_Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Property_Package_Enthalpy_Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Property Package Entropy Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Property_Package_Entropy_Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Property_Package_Entropy_Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Property Package Equilibrium Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Property_Package_Equilibrium_Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Property_Package_Equilibrium_Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Property Package Fugacity Coefficient Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Property_Package_Fugacity_Coefficient_Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Property_Package_Fugacity_Coefficient_Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PS Flash Newton Iteration.
        '''</summary>
        Public Shared ReadOnly Property PS_Flash_Newton_Iteration() As String
            Get
                Return ResourceManager.GetString("PS_Flash_Newton_Iteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PT Flash Newton Iteration.
        '''</summary>
        Public Shared ReadOnly Property PT_Flash_Newton_Iteration() As String
            Get
                Return ResourceManager.GetString("PT_Flash_Newton_Iteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recalculating the temporary material stream and moving on to the next segment/increment....
        '''</summary>
        Public Shared ReadOnly Property Recalculating_the_temporary_material_stream_and_moving_on_to_the_next_segment_increment() As String
            Get
                Return ResourceManager.GetString("Recalculating_the_temporary_material_stream_and_moving_on_to_the_next_segment_inc"& _ 
                        "rement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;h2&gt;Results&lt;/h2&gt;.
        '''</summary>
        Public Shared ReadOnly Property Results() As String
            Get
                Return ResourceManager.GetString("Results", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Segment #{0} ({1}/{2}).
        '''</summary>
        Public Shared ReadOnly Property Segment_0_1_2() As String
            Get
                Return ResourceManager.GetString("Segment_0_1_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Segment increments: {0}.
        '''</summary>
        Public Shared ReadOnly Property Segment_increments_0() As String
            Get
                Return ResourceManager.GetString("Segment_increments_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Segment type: {0}.
        '''</summary>
        Public Shared ReadOnly Property Segment_type_0() As String
            Get
                Return ResourceManager.GetString("Segment_type_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting Liquid Phase Stability Test @ T = {0} K &amp; P = {1} Pa for the following trial phases:.
        '''</summary>
        Public Shared ReadOnly Property Starting_Liquid_Phase_Stability_Test_T_0_K_P_1_Pa_for_the_following_trial_phases() As String
            Get
                Return ResourceManager.GetString("Starting_Liquid_Phase_Stability_Test_T_0_K_P_1_Pa_for_the_following_trial_phases", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State {0}.
        '''</summary>
        Public Shared ReadOnly Property State_0() As String
            Get
                Return ResourceManager.GetString("State_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temperature: {0} K.
        '''</summary>
        Public Shared ReadOnly Property Temperature_0_K() As String
            Get
                Return ResourceManager.GetString("Temperature_0_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temperature convergence loop iteration #{0}.
        '''</summary>
        Public Shared ReadOnly Property Temperature_convergence_loop_iteration_0() As String
            Get
                Return ResourceManager.GetString("Temperature_convergence_loop_iteration_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temperature Loop #{0}.
        '''</summary>
        Public Shared ReadOnly Property Temperature_Loop_0() As String
            Get
                Return ResourceManager.GetString("Temperature_Loop_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temporary Object.
        '''</summary>
        Public Shared ReadOnly Property Temporary_Object() As String
            Get
                Return ResourceManager.GetString("Temporary_Object", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The algorithm converged in {0} iterations. Time taken: {1} ms..
        '''</summary>
        Public Shared ReadOnly Property The_algorithm_converged_in_0_iterations_Time_taken_1_ms() As String
            Get
                Return ResourceManager.GetString("The_algorithm_converged_in_0_iterations_Time_taken_1_ms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The compressibility factor (liquid or vapor) can be obtained from the equation.
        '''</summary>
        Public Shared ReadOnly Property The_compressibility_factor_liquid_or_vapor_can_be_obtained_from_the_equation() As String
            Get
                Return ResourceManager.GetString("The_compressibility_factor_liquid_or_vapor_can_be_obtained_from_the_equation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The PH Flash algorithm converged in {0} iterations. Final Temperature value: {1} K.
        '''</summary>
        Public Shared ReadOnly Property The_PH_Flash_algorithm_converged_in_0_iterations_Final_Temperature_value_1_K() As String
            Get
                Return ResourceManager.GetString("The_PH_Flash_algorithm_converged_in_0_iterations_Final_Temperature_value_1_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This Is the external loop To converge pressure When outlet temperature Is specified Or vice-versa..
        '''</summary>
        Public Shared ReadOnly Property This_Is_the_external_loop_To_converge_pressure_When_outlet_temperature_Is_specified_Or_vice_versa() As String
            Get
                Return ResourceManager.GetString("This_Is_the_external_loop_To_converge_pressure_When_outlet_temperature_Is_specifi"& _ 
                        "ed_Or_vice_versa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updated outlet pressure: {0} Pa.
        '''</summary>
        Public Shared ReadOnly Property Updated_outlet_pressure_0_Pa() As String
            Get
                Return ResourceManager.GetString("Updated_outlet_pressure_0_Pa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updated Temperature estimate: {0} K.
        '''</summary>
        Public Shared ReadOnly Property Updated_Temperature_estimate_0_K() As String
            Get
                Return ResourceManager.GetString("Updated_Temperature_estimate_0_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vapor Phase Compressibility Factor: {0}.
        '''</summary>
        Public Shared ReadOnly Property Vapor_Phase_Compressibility_Factor_0() As String
            Get
                Return ResourceManager.GetString("Vapor_Phase_Compressibility_Factor_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vapor Phase Cp = {0} kJ/[kg.K].
        '''</summary>
        Public Shared ReadOnly Property Vapor_Phase_Cp_0_kJ_kg_K() As String
            Get
                Return ResourceManager.GetString("Vapor_Phase_Cp_0_kJ_kg_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vapor Phase Density.
        '''</summary>
        Public Shared ReadOnly Property Vapor_Phase_Density() As String
            Get
                Return ResourceManager.GetString("Vapor_Phase_Density", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vapor Phase Density = {0} kg/m3.
        '''</summary>
        Public Shared ReadOnly Property Vapor_Phase_Density_0_kg_m3() As String
            Get
                Return ResourceManager.GetString("Vapor_Phase_Density_0_kg_m3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vapor Phase Density Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Vapor_Phase_Density_Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Vapor_Phase_Density_Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vapor Phase Thermal Conductivity = {0} W/[m.K].
        '''</summary>
        Public Shared ReadOnly Property Vapor_Phase_Thermal_Conductivity_0_W_m_K() As String
            Get
                Return ResourceManager.GetString("Vapor_Phase_Thermal_Conductivity_0_W_m_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vapor Phase Velocity = {0} m/s.
        '''</summary>
        Public Shared ReadOnly Property Vapor_Phase_Velocity_0_m_s() As String
            Get
                Return ResourceManager.GetString("Vapor_Phase_Velocity_0_m_s", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to where:.
        '''</summary>
        Public Shared ReadOnly Property where() As String
            Get
                Return ResourceManager.GetString("where", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
