'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class SolutionInspector
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DWSIM.Interfaces.SolutionInspector", GetType(SolutionInspector).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Acentric Factors: {0}.
        '''</summary>
        Public Shared ReadOnly Property Acentric_Factors_0() As String
            Get
                Return ResourceManager.GetString("Acentric_Factors_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;h2&gt;Calculated Intermediate Parameters&lt;/h2&gt;.
        '''</summary>
        Public Shared ReadOnly Property Calculated_Intermediate_Parameters() As String
            Get
                Return ResourceManager.GetString("Calculated_Intermediate_Parameters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;h2&gt;Calculated Parameters&lt;/h2&gt;.
        '''</summary>
        Public Shared ReadOnly Property Calculated_Parameters() As String
            Get
                Return ResourceManager.GetString("Calculated_Parameters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculation Type: {0}.
        '''</summary>
        Public Shared ReadOnly Property Calculation_Type_0() As String
            Get
                Return ResourceManager.GetString("Calculation_Type_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compounds: {0}.
        '''</summary>
        Public Shared ReadOnly Property Compounds_0() As String
            Get
                Return ResourceManager.GetString("Compounds_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compressibility Factor.
        '''</summary>
        Public Shared ReadOnly Property Compressibility_Factor() As String
            Get
                Return ResourceManager.GetString("Compressibility_Factor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compressibility Factor: {0}.
        '''</summary>
        Public Shared ReadOnly Property Compressibility_Factor_0() As String
            Get
                Return ResourceManager.GetString("Compressibility_Factor_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compressibility Factor Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Compressibility_Factor_Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Compressibility_Factor_Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Critical Pressures: {0} Pa&quot;.
        '''</summary>
        Public Shared ReadOnly Property Critical_Pressures_0_Pa() As String
            Get
                Return ResourceManager.GetString("Critical_Pressures_0_Pa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Critical Temperatures: {0} K.
        '''</summary>
        Public Shared ReadOnly Property Critical_Temperatures_0_K() As String
            Get
                Return ResourceManager.GetString("Critical_Temperatures_0_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enthalpy: {0} kJ/kg.
        '''</summary>
        Public Shared ReadOnly Property Enthalpy_0_kJ_kg() As String
            Get
                Return ResourceManager.GetString("Enthalpy_0_kJ_kg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to External Diameter = {0} m.
        '''</summary>
        Public Shared ReadOnly Property External_Diameter_0_m() As String
            Get
                Return ResourceManager.GetString("External_Diameter_0_m", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to External HTC = {0} W/[m2.K].
        '''</summary>
        Public Shared ReadOnly Property External_HTC_0_W_m2_K() As String
            Get
                Return ResourceManager.GetString("External_HTC_0_W_m2_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to External Loop #{0}.
        '''</summary>
        Public Shared ReadOnly Property External_Loop_0() As String
            Get
                Return ResourceManager.GetString("External_Loop_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to External Temperature = {0} K.
        '''</summary>
        Public Shared ReadOnly Property External_Temperature_0_K() As String
            Get
                Return ResourceManager.GetString("External_Temperature_0_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flow Regime:.
        '''</summary>
        Public Shared ReadOnly Property Flow_Regime() As String
            Get
                Return ResourceManager.GetString("Flow_Regime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fluid Temperature = {0} K.
        '''</summary>
        Public Shared ReadOnly Property Fluid_Temperature_0_K() As String
            Get
                Return ResourceManager.GetString("Fluid_Temperature_0_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ideal Gas Heat Capacities: {0}.
        '''</summary>
        Public Shared ReadOnly Property Ideal_Gas_Heat_Capacities_0() As String
            Get
                Return ResourceManager.GetString("Ideal_Gas_Heat_Capacities_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Include External HTC = {0}.
        '''</summary>
        Public Shared ReadOnly Property Include_External_HTC_0() As String
            Get
                Return ResourceManager.GetString("Include_External_HTC_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Include Insulation = {0}.
        '''</summary>
        Public Shared ReadOnly Property Include_Insulation_0() As String
            Get
                Return ResourceManager.GetString("Include_Insulation_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Include Internal HTC = {0}.
        '''</summary>
        Public Shared ReadOnly Property Include_Internal_HTC_0() As String
            Get
                Return ResourceManager.GetString("Include_Internal_HTC_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Include Pipe Wall = {0}.
        '''</summary>
        Public Shared ReadOnly Property Include_Pipe_Wall_0() As String
            Get
                Return ResourceManager.GetString("Include_Pipe_Wall_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;h3&gt;Inlet Stream #{0}&lt;/h3&gt;.
        '''</summary>
        Public Shared ReadOnly Property Inlet_Stream_0() As String
            Get
                Return ResourceManager.GetString("Inlet_Stream_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;h2&gt;Input Parameters&lt;/h2&gt;.
        '''</summary>
        Public Shared ReadOnly Property Input_Parameters() As String
            Get
                Return ResourceManager.GetString("Input_Parameters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interaction Parameters: {0}.
        '''</summary>
        Public Shared ReadOnly Property Interaction_Parameters_0() As String
            Get
                Return ResourceManager.GetString("Interaction_Parameters_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;h2&gt;Intermediate Calculations&lt;/h2&gt;.
        '''</summary>
        Public Shared ReadOnly Property Intermediate_Calculations() As String
            Get
                Return ResourceManager.GetString("Intermediate_Calculations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Internal Diameter = {0} m.
        '''</summary>
        Public Shared ReadOnly Property Internal_Diameter_0_m() As String
            Get
                Return ResourceManager.GetString("Internal_Diameter_0_m", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Internal HTC = {0} W/[m2.K].
        '''</summary>
        Public Shared ReadOnly Property Internal_HTC_0_W_m2_K() As String
            Get
                Return ResourceManager.GetString("Internal_HTC_0_W_m2_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Length = {0} m.
        '''</summary>
        Public Shared ReadOnly Property Length_0_m() As String
            Get
                Return ResourceManager.GetString("Length_0_m", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liquid Holdup = {0}.
        '''</summary>
        Public Shared ReadOnly Property Liquid_Holdup_0() As String
            Get
                Return ResourceManager.GetString("Liquid_Holdup_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liquid Phase Cp = {0} kJ/[kg.K].
        '''</summary>
        Public Shared ReadOnly Property Liquid_Phase_Cp_0_kJ_kg_K() As String
            Get
                Return ResourceManager.GetString("Liquid_Phase_Cp_0_kJ_kg_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liquid Phase Density = {0} kg/m3.
        '''</summary>
        Public Shared ReadOnly Property Liquid_Phase_Density_0_kg_m3() As String
            Get
                Return ResourceManager.GetString("Liquid_Phase_Density_0_kg_m3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liquid Phase Thermal Conductivity = {0} W/[m.K].
        '''</summary>
        Public Shared ReadOnly Property Liquid_Phase_Thermal_Conductivity_0_W_m_K() As String
            Get
                Return ResourceManager.GetString("Liquid_Phase_Thermal_Conductivity_0_W_m_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liquid Phase Velocity = {0} m/s.
        '''</summary>
        Public Shared ReadOnly Property Liquid_Phase_Velocity_0_m_s() As String
            Get
                Return ResourceManager.GetString("Liquid_Phase_Velocity_0_m_s", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mass Flow: {0} kg/s.
        '''</summary>
        Public Shared ReadOnly Property Mass_Flow_0_kg_s() As String
            Get
                Return ResourceManager.GetString("Mass_Flow_0_kg_s", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mole Fractions: {0}.
        '''</summary>
        Public Shared ReadOnly Property Mole_Fractions_0() As String
            Get
                Return ResourceManager.GetString("Mole_Fractions_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overal Heat Transfer Coefficient Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Overal_Heat_Transfer_Coefficient_Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Overal_Heat_Transfer_Coefficient_Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overall HTC = {0} W/[m2.K].
        '''</summary>
        Public Shared ReadOnly Property Overall_HTC_0_W_m2_K() As String
            Get
                Return ResourceManager.GetString("Overall_HTC_0_W_m2_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Peng-Robinson EOS Fugacity Coefficient.
        '''</summary>
        Public Shared ReadOnly Property Peng_Robinson_EOS_Fugacity_Coefficient() As String
            Get
                Return ResourceManager.GetString("Peng_Robinson_EOS_Fugacity_Coefficient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Peng-Robinson EOS Heat Capacity Ratio Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Peng_Robinson_EOS_Heat_Capacity_Ratio_Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Peng_Robinson_EOS_Heat_Capacity_Ratio_Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Petalas and Aziz Multiphase Pressure Drop Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Petalas_and_Aziz_Multiphase_Pressure_Drop_Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Petalas_and_Aziz_Multiphase_Pressure_Drop_Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Petalas and Aziz Pressure Drop.
        '''</summary>
        Public Shared ReadOnly Property Petalas_and_Aziz_Pressure_Drop() As String
            Get
                Return ResourceManager.GetString("Petalas_and_Aziz_Pressure_Drop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phase 1 composition: {0}.
        '''</summary>
        Public Shared ReadOnly Property Phase_1_composition_0() As String
            Get
                Return ResourceManager.GetString("Phase_1_composition_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phase 2 composition: {0}.
        '''</summary>
        Public Shared ReadOnly Property Phase_2_composition_0() As String
            Get
                Return ResourceManager.GetString("Phase_2_composition_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Pipe Segment unit operation  can be used to 
        '''                                simulate fluid flow process in a pipe. Two of the most used 
        '''                                correlations for the calculation of pressure drop are available 
        '''                                in DWSIM. Temperature can be rigorously calculated considering 
        '''                                the influence of the environment. With the help of the Recycle 
        '''                                Logical Operation, the user can build large  [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_01() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The pipe segment is divided in sections, which can be straight 
        '''                                tubes, valves, curves, etc. Each section is subdivided in small 
        '''                                sections for calculation purposes, as defined by the user..
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_02() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The pipe segment is calculated based on incremental mass and 
        '''                            energy balances. The complete algorithm consists in three nested 
        '''                            loops. The external loop iterates on the sections (increments), 
        '''                            the middle loop iterates on the temperature and the internal loop 
        '''                            calculates the pressure. The pressure and temperature are 
        '''                            calculated as follows:.
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_03() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1. The inlet temperature and pressure are used to estimate the 
        '''                            increment outlet pressure and temperature..
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_04() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2. Fluid properties are calculated based in a arithmetic mean of 
        '''                            inlet and outlet conditions..
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_05() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3. The calculated properties and the inlet pressure are used to 
        '''                              calculate the pressure drop. With it, the outlet pressure is 
        '''                              calculated..
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_06() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4. The calculated and estimated pressure are compared, and if 
        '''                              their difference exceeds the tolerance, a new outlet pressure 
        '''                              is estimated, and the steps 2 and 3 are repeated..
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_07() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5. Once the internal loop has converged, the outlet temperature 
        '''                              is calculated. If the global heat transfer coefficient (U) was 
        '''                              given, the outlet temperature is calculated from the following 
        '''                              equation:.
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_08() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to where: Q = heat transferred, A = heat transfer area (external 
        '''                              surface) and `\Delta T_{ml}` = logarithmic mean temperature 
        '''                              difference..
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_09() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 6. The calculated temperature is compared to the estimated one, 
        '''                              and if their difference exceeds the specified tolerance, a new 
        '''                              temperature is estimated and new properties are calculated 
        '''                              (return to step 2)..
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_10() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 7. When both pressure and temperature converges, the results are 
        '''                            passed to the next increment, where calculation restarts..
        '''</summary>
        Public Shared ReadOnly Property Pipe_Calculate_Paragraph_11() As String
            Get
                Return ResourceManager.GetString("Pipe_Calculate_Paragraph_11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pipe Insulation HTC = {0} W/[m2.K].
        '''</summary>
        Public Shared ReadOnly Property Pipe_Insulation_HTC_0_W_m2_K() As String
            Get
                Return ResourceManager.GetString("Pipe_Insulation_HTC_0_W_m2_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pipe Roughness = {0} m.
        '''</summary>
        Public Shared ReadOnly Property Pipe_Roughness_0_m() As String
            Get
                Return ResourceManager.GetString("Pipe_Roughness_0_m", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pipe Wall HTC = {0} W/[m2.K].
        '''</summary>
        Public Shared ReadOnly Property Pipe_Wall_HTC_0_W_m2_K() As String
            Get
                Return ResourceManager.GetString("Pipe_Wall_HTC_0_W_m2_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pipe Wall Material = {0}.
        '''</summary>
        Public Shared ReadOnly Property Pipe_Wall_Material_0() As String
            Get
                Return ResourceManager.GetString("Pipe_Wall_Material_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pressure: {0} Pa.
        '''</summary>
        Public Shared ReadOnly Property Pressure_0_Pa() As String
            Get
                Return ResourceManager.GetString("Pressure_0_Pa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Property Package Enthalpy Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Property_Package_Enthalpy_Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Property_Package_Enthalpy_Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Property Package Entropy Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Property_Package_Entropy_Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Property_Package_Entropy_Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Property Package Fugacity Coefficient Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Property_Package_Fugacity_Coefficient_Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Property_Package_Fugacity_Coefficient_Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;h2&gt;Results&lt;/h2&gt;.
        '''</summary>
        Public Shared ReadOnly Property Results() As String
            Get
                Return ResourceManager.GetString("Results", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting Liquid Phase Stability Test @ T = {0} K &amp; P = {1} Pa for the following trial phases:.
        '''</summary>
        Public Shared ReadOnly Property Starting_Liquid_Phase_Stability_Test_T_0_K_P_1_Pa_for_the_following_trial_phases() As String
            Get
                Return ResourceManager.GetString("Starting_Liquid_Phase_Stability_Test_T_0_K_P_1_Pa_for_the_following_trial_phases", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State {0}.
        '''</summary>
        Public Shared ReadOnly Property State_0() As String
            Get
                Return ResourceManager.GetString("State_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temperature: {0} K.
        '''</summary>
        Public Shared ReadOnly Property Temperature_0_K() As String
            Get
                Return ResourceManager.GetString("Temperature_0_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The compressibility factor (liquid or vapor) can be obtained from the equation.
        '''</summary>
        Public Shared ReadOnly Property The_compressibility_factor_liquid_or_vapor_can_be_obtained_from_the_equation() As String
            Get
                Return ResourceManager.GetString("The_compressibility_factor_liquid_or_vapor_can_be_obtained_from_the_equation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This Is the external loop To converge pressure When outlet temperature Is specified Or vice-versa..
        '''</summary>
        Public Shared ReadOnly Property This_Is_the_external_loop_To_converge_pressure_When_outlet_temperature_Is_specified_Or_vice_versa() As String
            Get
                Return ResourceManager.GetString("This_Is_the_external_loop_To_converge_pressure_When_outlet_temperature_Is_specifi"& _ 
                        "ed_Or_vice_versa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vapor Phase Compressibility Factor: {0}.
        '''</summary>
        Public Shared ReadOnly Property Vapor_Phase_Compressibility_Factor_0() As String
            Get
                Return ResourceManager.GetString("Vapor_Phase_Compressibility_Factor_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vapor Phase Cp = {0} kJ/[kg.K].
        '''</summary>
        Public Shared ReadOnly Property Vapor_Phase_Cp_0_kJ_kg_K() As String
            Get
                Return ResourceManager.GetString("Vapor_Phase_Cp_0_kJ_kg_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vapor Phase Density.
        '''</summary>
        Public Shared ReadOnly Property Vapor_Phase_Density() As String
            Get
                Return ResourceManager.GetString("Vapor_Phase_Density", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vapor Phase Density = {0} kg/m3.
        '''</summary>
        Public Shared ReadOnly Property Vapor_Phase_Density_0_kg_m3() As String
            Get
                Return ResourceManager.GetString("Vapor_Phase_Density_0_kg_m3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vapor Phase Density Calculation Routine.
        '''</summary>
        Public Shared ReadOnly Property Vapor_Phase_Density_Calculation_Routine() As String
            Get
                Return ResourceManager.GetString("Vapor_Phase_Density_Calculation_Routine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vapor Phase Thermal Conductivity = {0} W/[m.K].
        '''</summary>
        Public Shared ReadOnly Property Vapor_Phase_Thermal_Conductivity_0_W_m_K() As String
            Get
                Return ResourceManager.GetString("Vapor_Phase_Thermal_Conductivity_0_W_m_K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vapor Phase Velocity = {0} m/s.
        '''</summary>
        Public Shared ReadOnly Property Vapor_Phase_Velocity_0_m_s() As String
            Get
                Return ResourceManager.GetString("Vapor_Phase_Velocity_0_m_s", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
