'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class UnitOperationsTranslate
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DWSIM.UnitOperations.UnitOperationsTranslate", GetType(UnitOperationsTranslate).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Annular Mist.
        '''</summary>
        Friend Shared ReadOnly Property PetalasAziz_FlowRegime_AnnularMist() As String
            Get
                Return ResourceManager.GetString("PetalasAziz_FlowRegime_AnnularMist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bubbles.
        '''</summary>
        Friend Shared ReadOnly Property PetalasAziz_FlowRegime_Bubbles() As String
            Get
                Return ResourceManager.GetString("PetalasAziz_FlowRegime_Bubbles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dispersed Bubbles.
        '''</summary>
        Friend Shared ReadOnly Property PetalasAziz_FlowRegime_DispersedBubbles() As String
            Get
                Return ResourceManager.GetString("PetalasAziz_FlowRegime_DispersedBubbles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Distributed.
        '''</summary>
        Friend Shared ReadOnly Property PetalasAziz_FlowRegime_Distributed() As String
            Get
                Return ResourceManager.GetString("PetalasAziz_FlowRegime_Distributed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Elongated Bubbles.
        '''</summary>
        Friend Shared ReadOnly Property PetalasAziz_FlowRegime_ElongatedBubbles() As String
            Get
                Return ResourceManager.GetString("PetalasAziz_FlowRegime_ElongatedBubbles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Froth.
        '''</summary>
        Friend Shared ReadOnly Property PetalasAziz_FlowRegime_Froth() As String
            Get
                Return ResourceManager.GetString("PetalasAziz_FlowRegime_Froth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Froth I (DB/AM transition).
        '''</summary>
        Friend Shared ReadOnly Property PetalasAziz_FlowRegime_Froth_I_DB_AM_transition() As String
            Get
                Return ResourceManager.GetString("PetalasAziz_FlowRegime_Froth_I_DB_AM_transition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Homogeneous.
        '''</summary>
        Friend Shared ReadOnly Property PetalasAziz_FlowRegime_Homogenous() As String
            Get
                Return ResourceManager.GetString("PetalasAziz_FlowRegime_Homogenous", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Intermittent.
        '''</summary>
        Friend Shared ReadOnly Property PetalasAziz_FlowRegime_Intermittent() As String
            Get
                Return ResourceManager.GetString("PetalasAziz_FlowRegime_Intermittent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liquid Only.
        '''</summary>
        Friend Shared ReadOnly Property PetalasAziz_FlowRegime_LiquidOnly() As String
            Get
                Return ResourceManager.GetString("PetalasAziz_FlowRegime_LiquidOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Segregated.
        '''</summary>
        Friend Shared ReadOnly Property PetalasAziz_FlowRegime_Segregated() As String
            Get
                Return ResourceManager.GetString("PetalasAziz_FlowRegime_Segregated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Single Phase.
        '''</summary>
        Friend Shared ReadOnly Property PetalasAziz_FlowRegime_Single_Phase() As String
            Get
                Return ResourceManager.GetString("PetalasAziz_FlowRegime_Single_Phase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Slug.
        '''</summary>
        Friend Shared ReadOnly Property PetalasAziz_FlowRegime_Slug() As String
            Get
                Return ResourceManager.GetString("PetalasAziz_FlowRegime_Slug", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stratified.
        '''</summary>
        Friend Shared ReadOnly Property PetalasAziz_FlowRegime_Stratified() As String
            Get
                Return ResourceManager.GetString("PetalasAziz_FlowRegime_Stratified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stratified Smooth.
        '''</summary>
        Friend Shared ReadOnly Property PetalasAziz_FlowRegime_StratifiedSmooth() As String
            Get
                Return ResourceManager.GetString("PetalasAziz_FlowRegime_StratifiedSmooth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stratified Waves.
        '''</summary>
        Friend Shared ReadOnly Property PetalasAziz_FlowRegime_StratifiedWaves() As String
            Get
                Return ResourceManager.GetString("PetalasAziz_FlowRegime_StratifiedWaves", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transition.
        '''</summary>
        Friend Shared ReadOnly Property PetalasAziz_FlowRegime_Transition() As String
            Get
                Return ResourceManager.GetString("PetalasAziz_FlowRegime_Transition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vapor Only.
        '''</summary>
        Friend Shared ReadOnly Property PetalasAziz_FlowRegime_VaporOnly() As String
            Get
                Return ResourceManager.GetString("PetalasAziz_FlowRegime_VaporOnly", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
