'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TCPServer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reservoir.Thermodynamic (симулятор химических и технологических процессов).
        '''</summary>
        Friend ReadOnly Property locAbout() As String
            Get
                Return ResourceManager.GetString("locAbout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Введите TCP-порт для приема заданий:.
        '''</summary>
        Friend ReadOnly Property locEnter_the_TCP_Port_Number_to_listen_to() As String
            Get
                Return ResourceManager.GetString("locEnter_the_TCP_Port_Number_to_listen_to", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server is running and listening to incoming data on port .
        '''</summary>
        Friend ReadOnly Property locTCPServer_Main_Server_is_running_and_listening_to_incoming_data_on_port() As String
            Get
                Return ResourceManager.GetString("locTCPServer_Main_Server_is_running_and_listening_to_incoming_data_on_port", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server IP Addresses:.
        '''</summary>
        Friend ReadOnly Property TCPServer_Main_Server_IP_Addresses() As String
            Get
                Return ResourceManager.GetString("TCPServer_Main_Server_IP_Addresses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculation aborted..
        '''</summary>
        Friend ReadOnly Property TCPServer_Process_Calculation_aborted() As String
            Get
                Return ResourceManager.GetString("TCPServer_Process_Calculation_aborted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Closing current session with .
        '''</summary>
        Friend ReadOnly Property TCPServer_Process_Closing_current_session_with() As String
            Get
                Return ResourceManager.GetString("TCPServer_Process_Closing_current_session_with", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Данные получены от.
        '''</summary>
        Friend ReadOnly Property TCPServer_Process_Data_received_from() As String
            Get
                Return ResourceManager.GetString("TCPServer_Process_Data_received_from", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error solving flowsheet: .
        '''</summary>
        Friend ReadOnly Property TCPServer_Process_Error_solving_flowsheet() As String
            Get
                Return ResourceManager.GetString("TCPServer_Process_Error_solving_flowsheet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to , расчет модели начался!.
        '''</summary>
        Friend ReadOnly Property TCPServer_Process_flowsheet_solving_started() As String
            Get
                Return ResourceManager.GetString("TCPServer_Process_flowsheet_solving_started", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Byte array length: .
        '''</summary>
        Friend ReadOnly Property TCPServer_ProcessData_Byte_array_length() As String
            Get
                Return ResourceManager.GetString("TCPServer_ProcessData_Byte_array_length", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
