'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Tips
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DWSIM.Tips", GetType(Tips).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If you want the Adjust Op to be automatically solved by the calculator, set the &quot;Simultaneous Adjust&quot; property to &quot;True&quot;. This way you won&apos;t need to open the Control Panel and your variable will be adjusted automatically whenever the flowsheet is calculated..
        '''</summary>
        Friend Shared ReadOnly Property ADJT001() As String
            Get
                Return ResourceManager.GetString("ADJT001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If you want to add some experimental data to the diagram, enter the data in the corresponding table before requesting the calculation..
        '''</summary>
        Friend Shared ReadOnly Property BENV001() As String
            Get
                Return ResourceManager.GetString("BENV001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The experimental data &quot;y&quot; column is used only in the xy diagrams. To show both experimental bubble and dew points in a T/P-xy diagram, enter all mole fractions in the &quot;x&quot; column..
        '''</summary>
        Friend Shared ReadOnly Property BENV002() As String
            Get
                Return ResourceManager.GetString("BENV002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The experimental data can be copied and pasted directly from Microsoft Excel..
        '''</summary>
        Friend Shared ReadOnly Property BENV003() As String
            Get
                Return ResourceManager.GetString("BENV003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When running simulations containing CAPE-OPEN unit ops in another computer, make sure that these components are installed and registered properly on it..
        '''</summary>
        Friend Shared ReadOnly Property CAPE001() As String
            Get
                Return ResourceManager.GetString("CAPE001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only kinetic type reactions will be considered by the CSTR..
        '''</summary>
        Friend Shared ReadOnly Property CSTR001() As String
            Get
                Return ResourceManager.GetString("CSTR001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To get help with scripts, take a look at the examples of Membrane and Hydrocyclone Unit Operations, located in the samples folder..
        '''</summary>
        Friend Shared ReadOnly Property CSUO001() As String
            Get
                Return ResourceManager.GetString("CSUO001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to It is recommended that the column propertiy editing be carried out with the calculator disabled..
        '''</summary>
        Friend Shared ReadOnly Property DCOL001() As String
            Get
                Return ResourceManager.GetString("DCOL001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When editing the column connections, remember to click any cell other than the one being edited, so that changes are recognized by DWSIM..
        '''</summary>
        Friend Shared ReadOnly Property DCOL002() As String
            Get
                Return ResourceManager.GetString("DCOL002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remember to set the pressure of the intermediate stages of the column..
        '''</summary>
        Friend Shared ReadOnly Property DCOL003() As String
            Get
                Return ResourceManager.GetString("DCOL003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Press F5 on any area inside the flowsheet to start a full calculation..
        '''</summary>
        Friend Shared ReadOnly Property FLSH001() As String
            Get
                Return ResourceManager.GetString("FLSH001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use the quick connection tool on the toolbar to quickly connect objects by pressing the CTRL key and dragging the cursor from the first to the second object..
        '''</summary>
        Friend Shared ReadOnly Property FLSH002() As String
            Get
                Return ResourceManager.GetString("FLSH002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hold SHIFT during DWSIM initialization to reset the settings to their default values..
        '''</summary>
        Friend Shared ReadOnly Property FLSH003() As String
            Get
                Return ResourceManager.GetString("FLSH003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to See some specific help for the object being added by selecting it in the flowsheet and pressing the F1 key. This also works for Utilities..
        '''</summary>
        Friend Shared ReadOnly Property FLSH004() As String
            Get
                Return ResourceManager.GetString("FLSH004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To view detailed results of the calculations in real time, enable console redirection and select a debug mode. You must restart DWSIM for the changes to take effect..
        '''</summary>
        Friend Shared ReadOnly Property FLSH005() As String
            Get
                Return ResourceManager.GetString("FLSH005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Some object types display their main editing window when you do a double-click on them in the flowsheet..
        '''</summary>
        Friend Shared ReadOnly Property FLSH006() As String
            Get
                Return ResourceManager.GetString("FLSH006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to After finishing updating the object connections, call the flowsheet solver by pressing the F5 key..
        '''</summary>
        Friend Shared ReadOnly Property FLSH007() As String
            Get
                Return ResourceManager.GetString("FLSH007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If some windows are missing, click on &apos;View&apos; &gt; &apos;Restore Layout&apos;..
        '''</summary>
        Friend Shared ReadOnly Property FLSH008() As String
            Get
                Return ResourceManager.GetString("FLSH008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The optimizer window can also be freely repositioned just like the flowsheet sub-windows..
        '''</summary>
        Friend Shared ReadOnly Property FOPT001() As String
            Get
                Return ResourceManager.GetString("FOPT001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The sensitivity analysis tool window can also be freely repositioned..
        '''</summary>
        Friend Shared ReadOnly Property FSAN001() As String
            Get
                Return ResourceManager.GetString("FSAN001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You can edit the composition of a material stream through a double click with the left mouse button..
        '''</summary>
        Friend Shared ReadOnly Property MSTR001() As String
            Get
                Return ResourceManager.GetString("MSTR001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The material stream context menu offers some useful tools for managing its data, such as copying data from another stream, restoring original data, exporting the data to the clipboard, etc..
        '''</summary>
        Friend Shared ReadOnly Property MSTR002() As String
            Get
                Return ResourceManager.GetString("MSTR002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To prevent the composition edit window from showing after adding a material stream, hold the SHIFT key while dropping it in the flowsheet..
        '''</summary>
        Friend Shared ReadOnly Property MSTR003() As String
            Get
                Return ResourceManager.GetString("MSTR003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When you request a calculation, all diagram types are calculated simultaneously. It isn&apos;t necessary to request another calculation if you want to see a different diagram on the screen..
        '''</summary>
        Friend Shared ReadOnly Property PENV001() As String
            Get
                Return ResourceManager.GetString("PENV001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only kinetic-type reactions will be taken into account by the PFR..
        '''</summary>
        Friend Shared ReadOnly Property PFR001() As String
            Get
                Return ResourceManager.GetString("PFR001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The properties shown on this tool are for DWSIM compounds only. CAPE-OPEN compound properties are not displayed here..
        '''</summary>
        Friend Shared ReadOnly Property PURE001() As String
            Get
                Return ResourceManager.GetString("PURE001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only the conversion reactions will be considered by the conversion reactor..
        '''</summary>
        Friend Shared ReadOnly Property RCON001() As String
            Get
                Return ResourceManager.GetString("RCON001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to It is important to properly define the location of the Recycle in the flowsheet, to avoid unnecessary calculations. Insert it into the nearest point where the calculation flow returns to an already calculated point..
        '''</summary>
        Friend Shared ReadOnly Property RECY001() As String
            Get
                Return ResourceManager.GetString("RECY001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The equilibrium reactor is used wherever the user has knowledge of the reactions that will occur. When that is not the case, use the Gibbs reactor..
        '''</summary>
        Friend Shared ReadOnly Property REQL001() As String
            Get
                Return ResourceManager.GetString("REQL001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to O reator de gibbs é útil quando não se tem informações a respeito das reações que poderão ocorrer no sistema. Lembre-se de que o simples fato de o resultado indicar algum tipo de reação não significa que essa reação será espontânea!.
        '''</summary>
        Friend Shared ReadOnly Property RGIB001() As String
            Get
                Return ResourceManager.GetString("RGIB001", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
